### ISSUE TITLE
.ogg not supported by safari

### ISSUE THREAD

**Issue by noahsark769** [calband/calchart-viewer#112] opened 2014-09-17 00:15 UTC
For some reason, it seems the FSM show .ogg isn't being accepted as a valid file on Safari. Possibly related to the file extension, more possible a bug in our validation code.

**Comment by brandonchinn178** [comment] 2015-09-25 16:02
just opening this up again, because we've got another response about safari and ogg. are we going to distribute other formats as well, or leave people wondering?

**Comment by noahsark769** [comment] 2015-09-26 00:17
I think having a warning show on safari is the best thing to do here if
safari can definitely not play ogg's

**Comment by brandonchinn178** [comment] 2015-09-26 00:20
:+1: see PR

**Comment by rmpowell77** [comment] 2015-09-27 07:15
Why not just convert the files to another format, like aac or mp3?  

Richard

**Comment by noahsark769** [comment] 2015-09-27 23:51
@rmpowell77: as I recall from last year, we were having some problems with how mp3 files you sometimes not get synced correctly with the animation, and the same problem didn't happen with oggs. (see #63). AAC could be another option: however, it wouldn't be bad to have this warning in any case.

**Comment by kmdurand** [comment] 2015-09-28 07:15
If I remember correctly, we stopped using MP3 files because they're encoded in a way that makes it difficult to begin playback from a particular moment of the music. When we asked our music player to begin playing music from some time xx:xx, it was only able to approximate the starting point in the file, so the music wasn't quite in sync with the animated dots.

**Comment by rmpowell77** [comment] 2015-09-28 07:36
Did some reading.  Ogg isn’t really the same as MP3.  Ogg is technically the container for the audio content, which is actually Vorbis.  As a container, Ogg probably contains an index table that a parser is able to decode and determine where particular offsets in a file are.  Vorbis is closer to what mp3 is, the encoded bitstream of audio data.

Mp3 has two interesting modes, Constant bit rate (CBR) and Variable bit rate (VBR).  With CBR, 1024 frames (23 ms @ 44.1 kHz) will take a fixed amount of bytes (more or less), but at VBR, it will take anywhere from 7 up to X, whatever the top bound by the encoder is set to based on the quality desired.  This means that if you have an MP3 file with VBR it is very hard to determine where the offset of the file at a particular time is, where to drop the needle, if you will.

MP4 is a container format specified by the MPEG standard, very much like Ogg.  MP4 can contain a wide variety of content formats, like MP3 and AAC.  MP4 files that contain just audio are often called M4A files.

So Ogg is to M4A as Vorbis is to MP3.

Perhaps the issue is that we should also support M4A or other container formats instead of MP3?

Richard

**Comment by kmdurand** [comment] 2015-09-28 07:55
Wow thanks @rmpowell77. With that in mind, I went again to go check out the audio file formats that are supported by different browsers, and I found [this chart](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility). It looks to me like AAC contained in MP4 seems like a good bet for us.

**Comment by brandonchinn178** [comment] 2016-09-01 02:32
Hmm it seems like using `.aac` files works pretty well. I tried the P!nk show again and it seems to at least work better than mp3.

Test files: [2014_p!nk_show.zip](https://github.com/calband/calchart-viewer/files/448706/2014_p.nk_show.zip)

Gonna close this as a good-for-now.

**Closed by brandonchinn178** 2016-09-01 02:32 UTC
Labels: bug, really-hard
